// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3VBS0eKRgTclR4TbAM1qXXqDFidUm6PA',
    appId: '1:1045727355485:web:baf1091597c0ba7114a3b4',
    messagingSenderId: '1045727355485',
    projectId: 'watertracker-3de4a',
    authDomain: 'watertracker-3de4a.firebaseapp.com',
    storageBucket: 'watertracker-3de4a.firebasestorage.app',
    measurementId: 'G-GG22VKK1HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlxBKbrNkLVZKKpZ7yNvq_tyFZd1oy6DM',
    appId: '1:1045727355485:android:e379af2078a3f7d114a3b4',
    messagingSenderId: '1045727355485',
    projectId: 'watertracker-3de4a',
    storageBucket: 'watertracker-3de4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz-2QUOilqN6e_lM81uprU6Uzn3_STyC0',
    appId: '1:1045727355485:ios:3a6ae53fe748cf7014a3b4',
    messagingSenderId: '1045727355485',
    projectId: 'watertracker-3de4a',
    storageBucket: 'watertracker-3de4a.firebasestorage.app',
    iosBundleId: 'com.example.waterTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz-2QUOilqN6e_lM81uprU6Uzn3_STyC0',
    appId: '1:1045727355485:ios:3a6ae53fe748cf7014a3b4',
    messagingSenderId: '1045727355485',
    projectId: 'watertracker-3de4a',
    storageBucket: 'watertracker-3de4a.firebasestorage.app',
    iosBundleId: 'com.example.waterTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3VBS0eKRgTclR4TbAM1qXXqDFidUm6PA',
    appId: '1:1045727355485:web:3274d3a732815a8214a3b4',
    messagingSenderId: '1045727355485',
    projectId: 'watertracker-3de4a',
    authDomain: 'watertracker-3de4a.firebaseapp.com',
    storageBucket: 'watertracker-3de4a.firebasestorage.app',
    measurementId: 'G-CSRGWZV2TV',
  );
}
